export const JACKPOT_PROTOCOL_ADDRESSES = {
  // 程序ID
  HARVEST_PROGRAM: "9NG3U16kwmQRtyW455gWspvTMwhMA96nReZmdHTc1NZo",
  SWAP_PROGRAM: "FASTZvUQgQYL5CSZvc6GLKDRe61mmoNX4F5Fe5qrDXGt",
  DISTRIBUTOR_PROGRAM: "E17zut6FKvX1CWp2vPZSgXUCaf7HbsgAprRKKs75FxRJ",
  POOL_PROGRAM: "9F8ezXUnTAKUXqvxSUBwrZqLZuRD96kURp323GHt91hU",
 
  // 代币Mint
  JACKPOT_MINT: "3MV6HCrWZe33mFcaNtpjK2HiHwegsjTYTLFZU8uJYyhq",
  USDC_MINT: "vJN93Z8XmkrhmyVtTdaNaAqzUm2stDAv2ooYrEkqRPa",
 
  // Harvest合约
  HARVEST_CONFIG: "8jk8f1saZidVzma4v8Pv6wPSEvNhDBNsWj9Mx1ZdPiUr",
  HARVEST_AUTHORITY: "F2p75ZW5oAZCgBDyiE4WdFAbnDvudEFruwS4uKxZZ78r",
  SWAP_TAX_ACCOUNT: "Dpp71Kz2k8grvHHBEHd6m1gapyuSwDFT7SGGb47kY1Zu",
 
  // Swap合约
  SWAP_CONFIG: "GHJpZzzQCG6oLWxKbx8dQ4dSZuuHq46tuw1mSeGh8cGN",
  SWAP_AUTHORITY: "HnM6zykkg8j8PhjfhS7oX3W9NaENNvpAmrrLaz44SdXa",
  SWAP_USDC_VAULT: "ASshmGRoLFALZfohQs3Qgg2Nx81J8d2XsXUGE8vcnw7h",
 
  // Distributor合约
  DISTRIBUTOR_CONFIG: "HWFwSh21aBh5539MT3EYDgQkH4Co7bzbFGB992V7hxGn",
  DISTRIBUTOR_AUTHORITY: "HEddKv2e9cgZRY1JhYXFntLFhqwu4tkxUu5QqnJEQA28",
  DISTRIBUTOR_VAULT: "2gxLC7jYGs9wBWMCFkkVBfwdMXDCYi4FQ2PK6DvrrTGq",
 
  // 资金池地址
  POOL_WEEKLY: "2wsXkzJtM7wnbotZ2sjNHiQzjSWiVHwqnackGHpWXdVQ",
  POOL_MONTHLY: "Fy1begTbD5YGKYYouX8KRE2AbWQ5ADSewM1vmRXeHm3N",
  POOL_STAKING: "7Cv41Hc61biPwRsxQDbkq8SqCJiXp19U6dfK8ju7tKJK",
  POOL_LIQUIDITY: "DyBZve3dprrRG9ZwiwcxvHnemcEA8uCta2oCeUn7ktkw",
  POOL_TEAM: "G9BUEKwkFJiusqV3yxdLzMKArPSDzhQjruo7BxjpCTCN",
 
  // Pool合约
  POOL_CONFIG: "ATBmThZz9AhDdDKHwLbrjPLUWAY9xCu19XBM9o1aiLHZ",
  POOL_VAULT: "CGcnsozFGNwqoXUCNjk9CSTnCCAQTTKHPi16fH4zrKVD",
  POOL_AUTHORITY: "5EM38m98sMbxhViEjupHGvGcFdXkeCmkZAgiSDDpq3rh",
 
  // 管理员地址
  OWNER: "9xN1DcpQeA3HzShZiiGq7kafuQPzU88gV86bsMo77iwp",
  // 添加 RPC_URL
  RPC_URL: "https://api.devnet.solana.com",
} as const;

// 新加：Solana devnet RPC URL
export const RPC_URL = 'https://api.devnet.solana.com';
